### ISSUE TITLE
Default RSS behavior may not be working

### ISSUE THREAD

**Issue by gimbi** [kaushikgopal/henry-hugo#5]
Great theme! 

I haven't been able to get RSS to work with default behavior, though I see it working on your personal blog. Can you test out-of-the-box RSS behavior and, if it's working as you expect, point me in the right direction?

**Comment by kaushikgopal** [comment]
@gimbi 🙏🏽 for the kind words.

🤔 hmm.. can you post your `config.toml` and i can debug it from there. for context, this is what the relevant parts of my `config.toml` look like:

```toml
[outputs]
    page = ["HTML"]
    home = ["HTML", "RSS", "JSON"]
    section = ["HTML","RSS"]
    taxonomyTerm = ["HTML"]
    taxonomy = ["HTML","RSS"]

[outputFormats]
[outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "feed"
```

beyond that i'm actually not doing any customizing. it's picking it up straight from [the rss.xm](https://github.com/kaushikgopal/henry-hugo/blob/master/layouts/_default/rss.xml)l here.
